language: ruby
cache:
  directories:
    - vendor/bundle
install:
  - bundle config gems.rapidrailsthemes.com $RRT_CREDENTIALS
  - bundle install --path vendor/bundle
  - RAILS_ENV=test rails db:create
